#cloud-config
users:
  # Real users
  - name: cosheehan
    lock_passwd: true
    groups: sudo
    shell: /bin/bash
    sudo:  ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDF1QPKh9Qe7uLewUXKJj66zwYngDJM3UbmyO/6jhdFSbsSB1528THQjZYjemj1JyWmvuKk7lCEJD06alGMN54jEm0qccjZEQc1jQ3ZIa6YZpEjHyFuqgIrTVj3N6LXBBbENOdSFt+V3WGRNw9cXq30rr8vD6tmk4+IjXgTHuTqyGCfTBIx48qvbC7CszF8CkoQYFGOHMpP9R/VN3BjTnOSf9ULIqyxZ0BNJ+SMtMYn+DKefOiNNtYsDz5GcjbJFnGidAw3/Zqpz19wrfKwIDfIBgAgrrYAMzYOawCFWINevhGbQUuUJNXk78ZC6ouiaenvtsPgC1hnxth3neazS0sX69wKIYP1ECZLK86dm4fSKVqkazjI2TyQ7T9NHAEbO0i6XUQhAaXC6hbTCa7uLknJY4/NkAL0s9G70lTlw/uRFhhlK44/fW5c7tURbgw5N3mGO5dYWL0xzFECSfQkiSWZBSBviD9rUh6FVRxFVpPE+HpDhEtVd0HoybXnFXr7Zrayfv6K4Xsls5JSrf149YVKr/mrXYbIY8MzaFRDO9Q9yoiNZcbIVe8wVhq+1afUA7ME/xbDzBxlaXmwflhs8lfeOgG8d9rgsgrXsRZFuIi2KLM420iaWk+/yhzjhg/ZrJ/2DFRKCbMdO3SYkBFwPr+QDQYs83nliGhuNqS4KTZMsw==
  - name: zzabaneh
    lock_passwd: true
    groups: sudo
    shell: /bin/bash
    sudo:  ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSeZQVfoIfLltuAau/D+F+SCWeBbXSs6q+lzbZjqOuEDlbSKU6sM6ZzyKX6ToBSyCe1fMqq2R0R/WC0HNSoCEuPJjJPwzs1qkdbDJc4mAioeRxHJ63Kl63bO7BztvRZhhgmdbN7/3tRzKlR9UzmyaGDmk9DtpYZZDeIAJxfwK5I1wT0gYUxN8TkSDZ1DEqxZ0UK7oHvWbzSNppvmuO87AzKbIxcmop5I6H/iJxnFBVAlxRR3qtSAL9dY/XQbHgIQTiLhC668uLzCFmsMyu8a4+6Es+I1t5X+YVOgD7pARgH16eP0tVNlkC0Msxj6bQBETgto1UQyWBpahDZOfeSK980Ixef6oqZa7FEpTocpoks3yYQjVrnfRCUSkO3EgCAPRTjTUPW8T/OZzW74rG831kwxKAX3nOlQWAh0UxuUcO5n31zT2TSjKHSK6rQHPYGTHZ8JviTdSbjhGDpUmjnhBKN0sBMCmdBz2i9UZdFQJ2ggYun6C+5QBTYIisGAcBqktJfdUob6lk9zV3aEJLHzI/zllhh5YXaCcaSN5QnJyQieDZn+ZI7AyZRyO6ybGIPeoZAp620fcgZv3xgjmjVoJlN7n69xOsYLMtroTQmWkPvXfF4mEDrzy3d0DHvXXTs7yrM6guaQoE6sT+51Ne7ENv2I/jPpadZnKSUszqoNWUkQ==
  # Other users
  - name: hg
    lock_passwd: true
    shell: /bin/bash

runcmd:
  # for now we need to copy the instance_data.json object on first boot
  # this is because cloud-init did not persist the instance_data.json
  # object until version 18.4, and version 18.2 is the latest available
  # on CentOS7
  - [ "mkdir", "/var/hg" ]
  - [ "cp", "/run/cloud-init/instance-data.json", "/var/hg/instance_data.json" ]
  - [ "chown", "hg:hg", "-R", "/var/hg" ]
